variables:
  DOCKER_TLS_CERTDIR: "/certs"

stages:
  - pages

pages :
  stage: pages
  when: manual
  image: node:18-alpine
  only:
    - tags
  before_script:
    - corepack enable
    - pnpm install
    - rm -rf public
    - mkdir public
  script:
    - node_modules/apidoc/bin/apidoc -i app -t ./resources/template-apidoc -o
      public
  artifacts:
    paths:
      # The folder that contains the files to be exposed at the Page URL
      - public
  # rules:
      # This ensures that only pushes to the default branch will trigger
      # a pages deploy
    #  - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
