packages:
  - "resources/frontend/vendor_modules/*/*"

allowBuilds:
  '@parcel/watcher': false
  canvas: false
  core-js: false
  ejs: false
  v-code-diff: true
  vue-demi: true
  vue-echarts: true

engineStrict: true

minimumReleaseAge: 0
