apiVersion: v2
name: cattr-server
description: Cattr is an open-source time-tracking solution for teams
type: application
version: 0.1.0
appVersion: "latest"
keywords:
  - cattr
  - time-tracking
  - productivity
  - management
  - laravel
home: https://cattr.app
sources:
  - https://github.com/cattr-app/server-application
  - https://git.amazingcat.net/cattr/core/app
